// data.js — Portfolio phase content
// Each phase maps to one robot assembly step

export const phases = [
  {
    id: 'intro',
    phase: '01',
    tag: 'SUMMARY',
    title: 'Shubh Khandelwal',
    content: `Specialized in autonomous navigation systems and embedded software for planetary exploration platforms. Currently contributing to next-generation Mars surface mobility architecture at JPL Research Division.`,
    content2: `Bridging the gap between simulation fidelity and physical deployment — crafting systems that work in both Gazebo virtual environments and the unforgiving terrain of real-world field tests.`,
    state: 'MPU Initialization',
  },
  {
    id: 'education',
    phase: '02',
    tag: 'EDUCATION & SKILLS',
    title: 'Educational Qualifications',
    content: `M.S. Robotics Engineering, Carnegie Mellon University (2021). B.S. Electrical & Computer Engineering, UC San Diego (2019). Relevant coursework in perception, motion planning, controls, and autonomous systems design.`,
    content2: `GPA: 3.94/4.0 — Graduate Research Fellowship recipient. Thesis: "Adaptive Terrain Classification for Wheeled Robots in Unstructured Environments."`,
    tags: ['PCB Design', 'RTOS', 'ARM Cortex', 'CAN Bus', 'I2C/SPI', 'OpenCV', 'TensorFlow Lite', 'Kalman Filtering'],
    timeline: [
      { title: 'M.S. Robotics Engineering — CMU', date: '2019 – 2021' },
      { title: 'B.S. ECE — UC San Diego', date: '2015 – 2019' },
    ],
    state: 'PCB Connection',
  },
  {
    id: 'experience',
    phase: '03',
    tag: 'EXPERIENCE',
    title: 'Work Experience',
    content: `Senior Software Engineer @ NASA JPL (2022–Present). Designed and deployed ROS2-based perception stack for Perseverance successor platform. Reduced terrain mapping latency by 43% through GPU-accelerated pointcloud processing.`,
    content2: `Robotics Engineer @ Boston Dynamics (2021–2022). Integrated multi-modal sensor fusion (LiDAR + stereo vision + IMU) for quadruped navigation. Authored 3 internal patents for proprioceptive feedback algorithms.`,
    tags: ['LiDAR', 'Stereo Vision', 'IMU Fusion', 'PointCloud Processing', 'SLAM', 'Nav2', 'MoveIt2'],
    timeline: [
      { title: 'Sr. Software Engineer — NASA JPL', date: '2022 – Present' },
      { title: 'Robotics Engineer — Boston Dynamics', date: '2021 – 2022' },
      { title: 'Research Assistant — CMU RI', date: '2019 – 2021' },
    ],
    state: 'Chassis Placement',
  },
  {
    id: 'projects',
    phase: '04',
    tag: 'PROJECTS',
    title: 'Developed Projects',
    content: `ARES-IV Autonomy Stack — Open-source ROS2 navigation framework for planetary rovers. 2,400+ GitHub stars, adopted by 7 university robotics programs. Features adaptive path planning under sensor degradation scenarios.`,
    content2: `SIM-REAL Bridge — A zero-downtime testing pipeline using domain randomization to transfer policies trained in Gazebo simulation directly to physical hardware, achieving 89% transfer success rate.`,
    tags: ['Path Planning', 'RRT*', 'A*', 'Domain Randomization', 'CI/CD', 'Docker', 'ROS2 Actions', 'Behavior Trees'],
    metrics: [
      { value: '2.4K', label: 'GITHUB STARS' },
      { value: '89%', label: 'SIM-REAL TRANSFER' },
      { value: '43%', label: 'LATENCY REDUCTION' },
      { value: '7', label: 'UNIVERSITY ADOPTIONS' },
    ],
    state: 'Sensor Addition',
  },
  {
    id: 'achievements',
    phase: '05',
    tag: 'ACHIEVEMENTS',
    title: 'Performance Benchmarks',
    content: `IEEE Robotics & Automation Society Best Paper Award (2023) — "Real-Time Adaptive Gait Optimization for Rough Terrain Traversal." Featured in IEEE Spectrum and MIT Technology Review.`,
    content2: `Finalist — NASA Centennial Challenge: Autonomous Robotics (2022). Top 3% ranking in international ROS2 robotics competition (2021). 4 peer-reviewed publications in top-tier robotics conferences.`,
    tags: ['IEEE Award', 'NASA Challenge', 'Publications', 'Patents', 'Open Source'],
    metrics: [
      { value: '#1', label: 'IEEE RA PAPER AWARD' },
      { value: '4', label: 'PUBLICATIONS' },
      { value: '3', label: 'PATENTS FILED' },
      { value: 'TOP 3%', label: 'GLOBAL RANKING' },
    ],
    state: 'Suspension Attachment',
  },
  {
    id: 'contact',
    phase: '06',
    tag: 'CONTACT',
    title: 'Contact Information',
    content: `Available for senior engineering roles, research collaborations, and consulting engagements in robotics, autonomous systems, and embedded software. Currently accepting technical advisory positions.`,
    content2: `Response time: 24–48 hours. Preferred channel: email for formal inquiries, GitHub for technical discussions and open-source collaboration requests.`,
    links: [
      { icon: '✉', label: 'alex.rivera@robotics.io', type: 'email', href: 'mailto:alex.rivera@robotics.io' },
      { icon: '⌥', label: 'github.com/alexrivera-robotics', type: 'github', href: 'https://github.com' },
      { icon: '◈', label: 'linkedin.com/in/alexrivera-eng', type: 'linkedin', href: 'https://linkedin.com' },
      { icon: '◉', label: '+1 (415) 867-5309', type: 'phone', href: 'tel:+14158675309' },
    ],
    state: 'Rover Activation',
  },
];